import { apiFetch } from './apiClient';
import type { Order, Payment } from './types/order';

export function listMyOrdersRequest(accessToken: string): Promise<{ orders: Order[] }> {
  return apiFetch<{ orders: Order[] }>('/orders', { accessToken });
}

export function shipOrderRequest(
  accessToken: string,
  orderId: string,
  shipment: { carrier: string; trackingNumber: string },
): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/ship`, { method: 'POST', body: shipment, accessToken });
}

export function confirmDeliveryRequest(accessToken: string, orderId: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/confirm-delivery`, { method: 'POST', accessToken });
}

export function getOrderRequest(accessToken: string, orderId: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}`, { accessToken });
}

// idempotencyKey is generated by the caller once per "Pay" attempt (Section
// 11 — mirrors placeBidRequest's own idempotencyKey pattern) — a retry of
// the SAME attempt (e.g. a disabled-button double-click racing the network)
// should reuse it; a genuinely fresh attempt (page reload, retry after a
// failed payment) should generate a new one. See app/orders/[id]/page.tsx.
export function payOrderRequest(accessToken: string, orderId: string, idempotencyKey: string): Promise<{ payment: Payment }> {
  return apiFetch<{ payment: Payment }>(`/orders/${orderId}/pay`, {
    method: 'POST',
    body: { idempotencyKey },
    accessToken,
  });
}
