import { apiFetch } from './apiClient';
import type { Order, Payment, ShippingAddress } from './types/order';

export function listMyOrdersRequest(accessToken: string): Promise<{ orders: Order[] }> {
  return apiFetch<{ orders: Order[] }>('/orders', { accessToken });
}

// The carrier and tracking number are assigned by the server's shipping
// provider (ADR-0045); the seller only says "it's shipped".
export function shipOrderRequest(accessToken: string, orderId: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/ship`, { method: 'POST', accessToken });
}

export function saveShippingAddressRequest(
  accessToken: string,
  orderId: string,
  address: ShippingAddress,
): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/shipping-address`, { method: 'PUT', body: address, accessToken });
}

// SELLER, with the 6-digit code the buyer was shown.
export function confirmDeliveryRequest(accessToken: string, orderId: string, code: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/confirm-delivery`, { method: 'POST', body: { code }, accessToken });
}

// BUYER: a fresh code (also unlocks an order locked by wrong guesses).
export function regenerateDeliveryCodeRequest(accessToken: string, orderId: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}/delivery-code/regenerate`, { method: 'POST', accessToken });
}

export function getOrderRequest(accessToken: string, orderId: string): Promise<{ order: Order }> {
  return apiFetch<{ order: Order }>(`/orders/${orderId}`, { accessToken });
}

// idempotencyKey is generated by the caller once per "Pay" attempt (Section
// 11 — mirrors placeBidRequest's own idempotencyKey pattern) — a retry of
// the SAME attempt (e.g. a disabled-button double-click racing the network)
// should reuse it; a genuinely fresh attempt (page reload, retry after a
// failed payment) should generate a new one. See app/orders/[id]/page.tsx.
// checkoutUrl is the payment provider's hosted page (Stripe Checkout); null
// when the provider settles by itself (the local mock).
export function payOrderRequest(
  accessToken: string,
  orderId: string,
  idempotencyKey: string,
): Promise<{ payment: Payment; checkoutUrl: string | null }> {
  return apiFetch<{ payment: Payment; checkoutUrl: string | null }>(`/orders/${orderId}/pay`, {
    method: 'POST',
    body: { idempotencyKey },
    accessToken,
  });
}

// Asks the server to check with the payment provider instead of waiting for
// its webhook. Safe to call repeatedly.
export function syncPaymentRequest(accessToken: string, orderId: string): Promise<{ synced: boolean }> {
  return apiFetch<{ synced: boolean }>(`/orders/${orderId}/payment/sync`, { method: 'POST', accessToken });
}
